/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nands
 */
public class Entry extends javax.swing.JFrame {

    int noOfPlayers;

    /**
     * Creates new form Entry
     */
    public Entry(int noOfPlayers) throws FileNotFoundException, IOException {
        initComponents();
        setSize(340, 380);
        player1Label.setVisible(false);
        player1Txt.setVisible(false);
        player2Label.setVisible(false);
        player2Txt.setVisible(false);

        File imgfile = new File("..\\TicTacToe\\src\\images\\flower.png");
        FileInputStream imgStream = new FileInputStream(imgfile);
        BufferedImage bi = ImageIO.read(imgStream);
        ImageIcon myImg = new ImageIcon(bi);
        this.setIconImage(myImg.getImage());
        setVisible(true);

        this.noOfPlayers = noOfPlayers;
    }

    private Entry() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void onePlayerEnable() {
        player1Label.setVisible(true);
        player1Txt.setVisible(true);
    }

    public void twoPlayerEnable() {
        player1Label.setVisible(true);
        player1Txt.setVisible(true);
        player2Label.setVisible(true);
        player2Txt.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startBtn = new javax.swing.JButton();
        player2Label = new javax.swing.JButton();
        player2Txt = new javax.swing.JTextField();
        player1Label = new javax.swing.JButton();
        player1Txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        getContentPane().setLayout(null);

        startBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        startBtn.setText("Start Game");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startBtn);
        startBtn.setBounds(90, 270, 140, 27);

        player2Label.setBackground(new java.awt.Color(204, 51, 0));
        player2Label.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        player2Label.setText("Player 2 : Name");
        player2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2));
        player2Label.setEnabled(false);
        player2Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2LabelActionPerformed(evt);
            }
        });
        getContentPane().add(player2Label);
        player2Label.setBounds(60, 160, 210, 30);

        player2Txt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        getContentPane().add(player2Txt);
        player2Txt.setBounds(60, 200, 210, 30);

        player1Label.setBackground(new java.awt.Color(204, 51, 0));
        player1Label.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        player1Label.setText("Player 1  : Name");
        player1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2));
        player1Label.setEnabled(false);
        player1Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1LabelActionPerformed(evt);
            }
        });
        getContentPane().add(player1Label);
        player1Label.setBounds(60, 40, 210, 30);

        player1Txt.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        player1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1TxtActionPerformed(evt);
            }
        });
        player1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                player1TxtKeyTyped(evt);
            }
        });
        getContentPane().add(player1Txt);
        player1Txt.setBounds(60, 80, 210, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cute-cherry-background.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 350);

        setSize(new java.awt.Dimension(352, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void player2LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2LabelActionPerformed

    private void player1LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1LabelActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        String player1 = "Computer";
        String player2 = "Computer";
        Game game;
        try {

            player1 = player1Txt.getText();
            player2 = player2Txt.getText();

            if ((player1.equals("") || player2.equals("")) && noOfPlayers == 2) {
                JOptionPane.showMessageDialog(null, "Please enter the names.", "Warning!", JOptionPane.OK_OPTION);
            } else if (player1.equals("") && noOfPlayers == 1) {
                JOptionPane.showMessageDialog(null, "Please enter the name.", "Warning!", JOptionPane.OK_OPTION);
            } else {
                game = new Game(player1, player2 , noOfPlayers);
                this.setVisible(false);                
            }

        } catch (IOException ex) {
            Logger.getLogger(Entry.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_startBtnActionPerformed

    private void player1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1TxtActionPerformed
       
    }//GEN-LAST:event_player1TxtActionPerformed

    private void player1TxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_player1TxtKeyTyped
        char c = evt.getKeyChar();
        if (player1Txt.getText().length() < 70) {
            if (c == java.awt.event.KeyEvent.VK_ENTER) {
                player2Txt.requestFocus(true);
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_player1TxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton player1Label;
    private javax.swing.JTextField player1Txt;
    private javax.swing.JButton player2Label;
    private javax.swing.JTextField player2Txt;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
