/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import controller.ScoreController;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Nands
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() throws FileNotFoundException, IOException, ClassNotFoundException, SQLException {
        initComponents();
        setSize(510, 500);
        File imgfile = new File("..\\TicTacToe\\src\\images\\flower.png");
        FileInputStream imgStream = new FileInputStream(imgfile);
        BufferedImage bi = ImageIO.read(imgStream);
        ImageIcon myImg = new ImageIcon(bi);
        this.setIconImage(myImg.getImage());
        setVisible(true);
        
        int best = ScoreController.getMaximumScore();
        String text = "Best Score : " + Integer.toString(best);
        bestScoreLbl.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        twoPlayerBtn = new javax.swing.JButton();
        onePlayerBtn = new javax.swing.JButton();
        scoreBtn = new javax.swing.JButton();
        bestScoreLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Best Score :  ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        getContentPane().setLayout(null);

        twoPlayerBtn.setBackground(new java.awt.Color(153, 255, 204));
        twoPlayerBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        twoPlayerBtn.setText("Two Players");
        twoPlayerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        twoPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPlayerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(twoPlayerBtn);
        twoPlayerBtn.setBounds(140, 270, 230, 50);

        onePlayerBtn.setBackground(new java.awt.Color(153, 255, 204));
        onePlayerBtn.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        onePlayerBtn.setText("One Player");
        onePlayerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        onePlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePlayerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(onePlayerBtn);
        onePlayerBtn.setBounds(140, 200, 230, 50);

        scoreBtn.setBackground(new java.awt.Color(153, 255, 204));
        scoreBtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        scoreBtn.setText("Other Scores");
        scoreBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBtnActionPerformed(evt);
            }
        });
        getContentPane().add(scoreBtn);
        scoreBtn.setBounds(360, 430, 120, 30);

        bestScoreLbl.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        bestScoreLbl.setForeground(new java.awt.Color(255, 255, 255));
        bestScoreLbl.setText("Best Score :  ");
        getContentPane().add(bestScoreLbl);
        bestScoreLbl.setBounds(50, 420, 240, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FINAL.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 480, 80);

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/christmas-polka-dots.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 510);

        setSize(new java.awt.Dimension(520, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void twoPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPlayerBtnActionPerformed
        Entry entry = null;
        try {
            entry = new Entry(2);
        } catch (IOException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        entry.twoPlayerEnable();
        this.setVisible(false);
    }//GEN-LAST:event_twoPlayerBtnActionPerformed

    private void onePlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onePlayerBtnActionPerformed
        Entry entry = null;
        try {
            entry = new Entry(1);
        } catch (IOException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        entry.onePlayerEnable();
        this.setVisible(false);
    }//GEN-LAST:event_onePlayerBtnActionPerformed

    private void scoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBtnActionPerformed
        
            try {
                try {
                    new ScoresList();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_scoreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LogIn().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestScoreLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton onePlayerBtn;
    private javax.swing.JButton scoreBtn;
    private javax.swing.JButton twoPlayerBtn;
    // End of variables declaration//GEN-END:variables
}
